p0deje/Maccy

Maccy/AppDelegate.swift, Maccy/Maccy.swift
initial maccy obj at init(). other wise 'maccy.stgart()' and  'maccy.popUp()' is not same obj.
fix it , and then 'refresh() at Maccy#popUp()' is unnecessary.
=> initial maccy obj once

README.md
I submitted a [maccy](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/maccy.rb) cask to Homebrew, so that it can be installed via:
```bash
brew cask install maccy
```
=> Add Homebrew cask and update readme with installation instructions

Maccy/Menu.swift
The new release partially fixed issue #16. The proposed changes will prevent the focus on "Clear" item on search if has no result.
=> Prevent auto focus on system items

Maccy/HistoryMenuItem.swift, MaccyTests/HistoryMenuItemTests.swift
This commit will show both prefix and suffix of an entry in clipboard
by dividing the string's input to show prefix to half max length and similarly
show the suffix for another half max length. The text in between is
truncated and replaced with ellipsis.
Fixes #139
=> Add display of prefix and suffix for clipboard entry

README.md
Thanks for Maccy, looks really cool!
Just a quick PR to change the Homebrew cask upgrade command for [the `2.6.0` upgrade](https://brew.sh/2020/12/01/homebrew-2.6.0/):
> All `brew cask` commands have been deprecated in favour of `brew` commands (with `--cask`) when necessary
=> Update command to install from Homebrew

Maccy/Clipboard.swift
=> Fix saving contents that are copied when ignoreEvents is enabled

Maccy/Preferences/zh-Hans.lproj/AppearancePreferenceViewController.strings, README.md
Update Chinese translation and add a keyboard indicator to `README.md` to make it clearer. I didn't realize that the comma <kbd>,</kbd> should be pressed and have spend more than an hour to figure out why long press <kbd>⌘</kbd> doesn't work.😣
Thank you for your great app!
=> Update Chinese Translation

Maccy/Preferences/es.lproj/AdvancedPreferenceViewController.strings
made a correction on the translation, in spanish it was "Borrar el historial al dejar de fumar" ("Clear history when quit smoking"), therefore the purpose of the button was not clear.
=> Translation correction

README.md
Latest versions of `brew` allow you to skip the cask argument and will install just fine. 👍
=> Simplify brew command for installation

Maccy/Menu.swift
This is done by finding the preceding visible view and computing from it the bounds of the selected menu item in window coordinates.
=> Align popover with the selected menu item

Maccy/MenuHeader/MenuHeaderView.swift
This avoids a sound from being played when the menu is closed or the settings are opened.
=> Some fixes to event handling in order to avoid system beeps

Maccy/Maccy.swift, Maccy/Menu.swift, Maccy/MenuHeader/MenuHeaderView.swift, MaccyTests/MenuTests.swift
Don't differentiate between different popup types in code paths. Instead the window just isn't adjusted in `adjustMenuWindowPosition()` if not necessary. I'm playing with an implementation for opening the menu at the current text cursor location and this makes it a bit easier. Generally I think this makes the code a bit easier to reason about.
=> Make location adjustment adaptable for new types

Maccy.xcodeproj/project.pbxproj, Maccy/HistoryMenuItem/PreviewMenuItem.swift, Maccy/Menu.swift
I didn't find a way to adapt the new code path for older versions. Hence as discussed this restores the codepath on these versions.
=> Fix popovers on pre-Sonoma

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
- Usage of issue template forms written in `YAML`.
- The primary goal is to save the maintainer's time by ensuring all necessary information is provided, thus reducing the need for trivial follow-up questions such as 'which version of 'Maccy' are you using?'
- A secondary goal is to provide the user with some guidance on what is expected in a 'Maccy' bug report.
- [Github Docs - Syntax for issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
https://github.com/LangLangBart/Maccy/issues/new/choose
=> issue templates

Maccy/PopupLocation.swift
Simulate adjustments made by the OS to ensure the popup window is fully contained on the current screen.
Fixes #707
=> Adjust popup position to clamp window into current screen region

README.md
Reverts p0deje/Maccy#755
style attribute does not work well on the GitHub README
=> Revert "Remove header underline in README"

Maccy.xcodeproj/project.pbxproj, Maccy/Extensions/Bundle+ApplicationName.swift, Maccy/Extensions/NSWorkspace+ApplicationName.swift, Maccy/Settings/IgnoreSettingsViewController/IgnoreApplicationsViewController.swift
1. Some app's name is different in Applications with Ignore app list(`VidHub` named `MediaCenter` in ignore app)
2. Chose the same app multiple times will have duplicate items
3. Icon view may shown cached image if the app is removed(last item in below screenshot)
=> Optimize ignore apps list view

Maccy.xcodeproj/project.pbxproj, Maccy/Extensions/Defaults.Keys+Names.swift, Maccy/Extensions/NSPoint+DefaultsSerializable.swift, Maccy/FloatingPanel.swift, Maccy/PopupPosition.swift, Maccy/Settings/AppearanceSettingsPane.swift, Maccy/Settings/ar.lproj/AppearanceSettings.strings, Maccy/Settings/bs.lproj/AppearanceSettings.strings, Maccy/Settings/cs.lproj/AppearanceSettings.strings, Maccy/Settings/de.lproj/AppearanceSettings.strings, Maccy/Settings/en.lproj/AppearanceSettings.strings, Maccy/Settings/es.lproj/AppearanceSettings.strings, Maccy/Settings/fr.lproj/AppearanceSettings.strings, Maccy/Settings/he.lproj/AppearanceSettings.strings, Maccy/Settings/hr.lproj/AppearanceSettings.strings, Maccy/Settings/it.lproj/AppearanceSettings.strings, Maccy/Settings/ja.lproj/AppearanceSettings.strings, Maccy/Settings/ko.lproj/AppearanceSettings.strings, Maccy/Settings/nb.lproj/AppearanceSettings.strings, Maccy/Settings/nl.lproj/AppearanceSettings.strings, Maccy/Settings/pt-BR.lproj/AppearanceSettings.strings, Maccy/Settings/ru.lproj/AppearanceSettings.strings, Maccy/Settings/th.lproj/AppearanceSettings.strings, Maccy/Settings/tr.lproj/AppearanceSettings.strings, Maccy/Settings/uk.lproj/AppearanceSettings.strings, Maccy/Settings/zh-Hans.lproj/AppearanceSettings.strings, Maccy/Settings/zh-Hant.lproj/AppearanceSettings.strings
Haven't yet updated all the translations. 
Also made it such that the window is no longer movable when "Last position" isn't selected as it may be confusing if moving the window has no effect (this may not be desirable, if so it can be reverted).
Some additional thought:
The window center method could be converted to "Presets" for `.lastPosition` together with the current default position of `.lastPosition`. I imagine this being an additional dropdown with Options `["Default", "Center", "Custom"]`, where `Custom` is selected if the window is moved. This way the reset button could also be removed as resetting is a matter of changing it back to `Default`.
=> Add option to remember the last window position

Maccy/Observables/AppState.swift, Maccy/Observables/History.swift, Maccy/Views/HistoryListView.swift
This should fix the issue described in the discussion https://github.com/p0deje/Maccy/discussions/818#discussion-6970531
> (Un)pinning item doesn't immediately scroll to the item. It does not seem to be a big deal and is quite hard to fix, so likely it will not be fixed in the final release.
Let me know if I misunderstood the issue.
=> Scroll to item after unpinning

Maccy/Extensions/Defaults.Keys+Names.swift, Maccy/Settings/StorageSettingsPane.swift
The default pasteboard types only contained `.string` but also checked for `.rtf` and `.html` when checking if text storage is enabled. I moved the association from storage type to pasteboard types into its own class which defines the single source of truth for the setting. This way further issues (e.g. if a new type for text is added) can be avoided.
Fixes #883
=> Fix text storage not being active by default 

Maccy/Observables/AppState.swift, Maccy/Views/ListItemView.swift
This fixes an issue where hovering over an item at the edge of the list it would cause it to be scrolled into view. I find this behaviour a bit irritating and it also causes stuttering when scrolling to far too the edge of the list.
=> Don’t scroll if selected through hovering

Maccy/Settings/AppearanceSettingsPane.swift
Fixes #1019 
The correct popup location is now selected if the screen value is changed. I also implemented the proposal of displaying the current screen selection in the picker. Caveat: The picker is too narrow to display most of the values. Should I increase the width of the picker?
https://github.com/user-attachments/assets/aa54539f-e335-4b4f-a236-0992ebd64442
=> Fix popupScreen selection

Maccy/Models/HistoryItem.swift
Fixes #1020 by ignoring `com.apple.linkpresentation.metadata` in `HistoryItem.supersedes(_)`.
=> Deduplicate Safari URL copies

Maccy/Settings/fr.lproj/AdvancedSettings.strings
I replace all straight quotes (') with curved quotes (’) for better typography. Apple uses curved quotes in French text. I translate "Turn off" with "Désactiver" (deactivate) better than "Éteindre" (extinguish).
=> Update AdvancedSettings.strings (fix French typos)

Maccy/Settings/fr.lproj/IgnoreSettings.strings
I replace all straight quotes (') with curved quotes (’) for better typography. Apple uses curved quotes in French text. I change some word in the translation (literate translation of "bullet-proof" is bad, "pasteboard types" is not "cardboard types").
=> Update IgnoreSettings.strings (fix French typos)

Maccy/Views/HistoryItemView.swift, Maccy/Views/ListItemTitleView.swift, Maccy/Views/ListItemView.swift
The title says it all. Make the pasteboard string still visible as text if it is detected to be a HEX color. Very useful when copying something that looks like it is a color but actually isn't :)
=> Make HEX Code visible next to the color image

Maccy/Settings/StorageSettingsPane.swift
Really a completion of 83fc71a, which enforces a maximum history size of 999 but only for changes made via the text field itself. In contrast, you can go up to 9999 via the stepper, since its upper bound in the range was never changed from 9999. 
It's obviously undesirable to have two different "maximum" values.
The change just narrows the stepper range from `1...9999` to `1...999`.
=> Match stepper max with text field max for history size

Maccy/FloatingPanel.swift
This PR sets the sharingType of the FloatingPanel window to .none, effectively preventing the window from being captured in screen recordings or screenshots by other apps.
Privacy & Security: This ensures that sensitive UI content shown in the floating panel cannot be recorded by screen capture tools.
User trust: Helps reinforce that the app respects user privacy and does not expose clipboard contents or UI overlays unintentionally.
macOS Support: The NSWindow.sharingType property is fully supported on macOS and allows a per-window decision on whether it can be shared.
Feature Request: https://github.com/p0deje/Maccy/issues/1126
Apple Developer Docs: https://developer.apple.com/documentation/appkit/nswindow/sharingtype-swift.property
=> Set window sharing type to .none to block screen capture

Maccy/Settings/fr.lproj/StorageSettings.strings
I replace all straight quotes (') with curved quotes (’) for better typography. Apple uses curved quotes in French text. I add plural to the French "Texte" (in fact, **Text** must probably be plural because **Files** and **Images** are plural).
=> Update StorageSettings.strings (fix French typos)
